import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{
        // backgroundImage: "url('https://png.pngtree.com/background/20230602/original/pngtree-poker-chips-forming-a-border-on-the-right-with-a-green-picture-image_2860845.jpg')",
        backgroundRepeat: "no-repeat",
        backgroundSize: "cover",
      }}>
        {children}
      </body>
    </html>
  );
}
